### ISSUE TITLE
issue in pause 

### ISSUE THREAD

**Issue by shahmirzali49** [starkdmi/download_manager#3]
as you can see I can't pause sometime. then I deleted the download with X icon then start again downloading and there is a problem. when the first time there is a problem.

it's iPhone 8 real device.

```
isolated_download_manager_flutter: ^1.0.3
 isolated_download_manager: ^1.0.3
```

```
data in static Map<String, String> links
    "ali imran":
        "https://download.quranicaudio.com/quran/abdullaah_3awwaad_al-juhaynee//003.mp3",
```

```
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E772610a darwin-x64, locale en-TR)
    • Flutter version 3.7.12 on channel stable at /Users/mirzali/fvm/versions/3.7.12
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (8 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] VS Code (version 1.79.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```
https://github.com/starkdmi/download_manager/assets/49102327/60d56084-2624-46a3-9e04-0e026280f876

**Comment by starkdmi** [comment]
@Shahmirzali-Huseynov, thank you for all the info, can confirm the issue on my environment, seems like a race condition in ```DownloadManager``` when fastly sending pause/resume commands.

**Comment by shahmirzali49** [comment]
@starkdmi Actually, I remember one time it happens when I do normally not like the video 😅(I did it just for catching the issue fastly).

**Comment by starkdmi** [comment]
Even at normal speed there is a time required to start/resume the downloading (like 1 to 5 sec - server processing and response). I will address the issue soon 👌

**Comment by shahmirzali49** [comment]
Thank you for your effort. 👍

**Comment by starkdmi** [comment]
Should be fixed by [download_task](https://github.com/starkdmi/resumable_download) package [fix](https://github.com/starkdmi/resumable_download/commit/5a9ab9824093fdc01019ba1576284f9524dc6af4).

**Comment by shahmirzali49** [comment]
Great 👍
