### ISSUE TITLE
HandshakeException

### ISSUE THREAD

**Issue by shahmirzali49** [starkdmi/download_manager#7]
can you disable certificate validation in http package?  ( you can do optional ).

I get this error for some URLs. but I want to download it anyway cause I know there is no problem.

for disabling certificate validation example : 

```
import 'dart:io';

class MyHttpOverrides extends HttpOverrides{
  @override
  HttpClient createHttpClient(SecurityContext? context){
    return super.createHttpClient(context)
      ..badCertificateCallback = (X509Certificate cert, String host, int port)=> true;
  }
}

void main() {
  HttpOverrides.global = new MyHttpOverrides();
  runApp(MyApp());
}
```

**Comment by starkdmi** [comment]
@Shahmirzali-Huseynov, can you implement this by passing the custom `HttpClient`?

An [example](https://github.com/starkdmi/download_manager/blob/main/example/isolated_download_manager_auth_example.dart#L26).

**Comment by shahmirzali49** [comment]
@starkdmi Yes, I can. but How can I disable certificate validation for the Custom client?

**Comment by starkdmi** [comment]
@Shahmirzali-Huseynov, here:
```Dart
import 'package:http/io_client.dart';

final httpClient = HttpClient()..badCertificateCallback = ((X509Certificate cert, String host, int port) => true);
final ioClient = IOClient(httpClient);
await manager.init(isolates: 1, directory: directory, client: ioClient);
```

**Comment by shahmirzali49** [comment]
thanks, @starkdmi
